services:
  jaeger:
    image: jaegertracing/jaeger:latest
    restart: no
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - "16686:16686"
      - "4318:4318"
    networks:
      - metrics

networks:
  metrics:
